import type { NextPage } from 'next';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import Image from 'next/image';
import RegisterForm from '../components/auth/RegisterForm';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const session = useSession();
  console.log(session);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session?.data ? (
        <div>{session.data.user?.user?.email}</div>
      ) : (
        <div>loading...</div>
      )}
    </div>
  );
};

export default Home;
